version: '3.7'

services:
  service-auth:
    image: deissh/api-micro-service-auth:1.0.0
    restart: on-failure
    depends_on:
      - postgres
    environment:
      GIN_MODE: "release"
      DB_HOST: "postgres"
      DB_NAME: "microapi"
      DB_USER: "toor"
      DB_PSW: "XJp3(adK}WnJ{Qtk"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

  postgres:
    image: postgres
    restart: on-failure
    volumes:
      - /var/lib/postgresql/micro-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: XJp3(adK}WnJ{Qtk
      POSTGRES_USER: toor
      POSTGRES_DB: microapi
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      placement:
        constraints: [node.role == manager]

  nginx:
    image: deissh/api-nginx
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - service-auth
