definitions:
  handlers.CreateResponse:
    properties:
      api:
        description: API version
        type: string
      token:
        $ref: '#/definitions/models.Token'
        type: object
    type: object
  handlers.Health:
    properties:
      alive:
        type: boolean
    type: object
  handlers.HealthResponse:
    properties:
      Health:
        $ref: '#/definitions/handlers.Health'
        type: object
      api:
        description: API version
        type: string
    type: object
  handlers.Ping:
    properties:
      id:
        type: string
      service:
        type: string
      time:
        type: string
    type: object
  handlers.PingResponse:
    properties:
      api:
        description: API version
        type: string
      ping:
        $ref: '#/definitions/handlers.Ping'
        type: object
    type: object
  handlers.ResponseData:
    properties:
      data:
        type: string
      status:
        type: integer
    type: object
  models.Token:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
      userId:
        type: integer
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/auth:
    post:
      consumes:
      - application/json
      description: Generate new access_token and refresh_token
      operationId: create-token
      parameters:
      - description: service version
        in: query
        name: api
        type: string
      - description: user email
        in: query
        name: email
        type: string
      - description: user password
        in: query
        name: password
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.CreateResponse'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ResponseData'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ResponseData'
            type: object
      summary: Create new token
  /api/health:
    get:
      consumes:
      - application/json
      operationId: get-service-health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HealthResponse'
            type: object
      summary: Show health service
  /api/ping:
    get:
      consumes:
      - application/json
      operationId: ping-service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.PingResponse'
            type: object
      summary: Ping service
